server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: work-manage-pro-api
    datasource:
      url: jdbc:mysql://localhost:3306/work_manage?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: root
      password: root
  jpa:
    open-in-view: true
    show-sql: true
  messages:
    basename: messages
  jackson:
    date-format: yyyy-MM-dd
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
